name: Build and Deploy to Docker Hub + EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.mainbackend
          push: true
          tags: anand687/exaildraw-backend:latest

     
      - name: Build & Push WS Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.wsbackend
          push: true
          tags: anand687/exaildraw-wsbackend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest images..."
             docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

            docker pull anand687/exaildraw-backend:latest
            docker pull anand687/exaildraw-wsbackend:latest

            echo "Stopping old containers..."
            docker stop api || true
            docker rm api || true
            docker stop ws || true
            docker rm ws || true

            echo "Starting API container..."
            docker run -d \
              --name api \
              --env-file ~/exaildraw-deploy/.env.backend \
              --network app-network \
              anand687/exaildraw-backend:latest

            echo "Starting WS container..."
            docker run -d \
              --name ws \
              --env-file ~/exaildraw-deploy/.env.ws \
              --network app-network \
              anand687/exaildraw-wsbackend:latest

            echo "Restarting nginx..."
            docker restart nginx || true

            echo "Deployment complete!"
