name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------
      # BUILD MAIN BACKEND IMAGE
      # -----------------------------
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.mainbackend
          push: true
          tags: anand687/exaildraw-backend:latest

      # -----------------------------
      # BUILD WS BACKEND IMAGE
      # -----------------------------
      - name: Build & Push WS Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.wsbackend
          push: true
          tags: anand687/exaildraw-wsbackend:latest

      # -----------------------------
      # VERIFY PUSHED IMAGES
      # -----------------------------
      - name: Verify images
        run: |
          docker pull anand687/exaildraw-backend:latest
          docker pull anand687/exaildraw-wsbackend:latest
